spring.application.name=backend
spring.application.name=backend

# Database - MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/smart_campus_db
# If authentication is required, use:
# spring.data.mongodb.uri=mongodb://user:password@localhost:27017/smart_campus_db


# Server
server.port=8080